site_name: AtomQC
site_description: Atomistic Calculations on Quantum Computers
site_url: https://atomgptlab.github.io/atomqc/
repo_url: https://github.com/atomgptlab/atomqc
repo_name: atomgptlab/atomqc
copyright: Copyright &copy; Kamal Choudhary

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - content.code.copy
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Installation: installation.md
  - Quick start: quickstart.md
  - Methods: methods.md
  - Example scripts: scripts.md
  - Testing: testing.md
  - Web app: web-app.md
  - Citation: citation.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
